version: '3'
services:
  flask-app:
    build:
      context: ./app
    ports:
      - "8080:8080"      
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb+srv://<username>:<password>@cluster0.hkohyfz.mongodb.net/<db name>"  #Indicate your mongo DB URI

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
